name: Send Daily Questions

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: send questions
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
        FRIEND_CHAT_ID: ${{ secrets.FRIEND_CHAT_ID }}
      run: python send_daily_questions.py
        
    - name: commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add progress.json
        git commit -m "Update progress"
        git push